language: node_js
node_js:
  - 'node'

cache:
- apt
- directories:
  - "$HOME/.electron"
addons:
  apt:
    packages:
    - wine

install:
  - travis_retry npm install

script:
  - ls

notifications:
  email:
    on_success: never

before_deploy: npm run build

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH}"
  file: 
    - "dist/ElectroHacker-osx-${TRAVIS_TAG}.zip"
    - "dist/ElectroHacker-linux-${TRAVIS_TAG}.zip"
    - "dist/ElectroHacker-windows-${TRAVIS_TAG}.zip"
  skip_cleanup: true
  on:
    tags: true