language: node_js
node_js:
  - 'node'

cache:
- apt
- directories:
  - "$HOME/.electron"
addons:
  apt:
    packages:
    - wine

install:
  - travis_retry npm install

script:
  - npm run build
  - ls
  - ls ./dist

notifications:
  email:
    on_success: never


deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH}"
  file: 
    - "ElectroHacker-osx-${TRAVIS_TAG}.zip"
    - "ElectroHacker-linux-${TRAVIS_TAG}.zip"
    - "ElectroHacker-windows-${TRAVIS_TAG}.zip"
  skip_cleanup: true
  on:
    tags: true