language: node_js
node_js:
  - 'node'

cache:
- apt
- directories:
  - "$HOME/.electron"
addons:
  apt:
    packages:
    - wine

install:
  - travis_retry npm install

script:
  - chmod +x tests/run.js 
  - npm test

notifications:
  email:
    on_success: never


deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true